---
title: "415 Project"
author: "Brendan Bebb"
date: "2022-11-16"
output: pdf_document 
---
```{r}
APPL = AAPL
resetdataset = function(APPL) {
  APPL <- APPL[,-1]
  for (i in 1:5) {
    APPL <- APPL[,-8]
  }
}
  resetdataset(APPL)
```

```{r}
APPL <- cbind(APPL, "t1")
#target 1 predictor
for (i in 1:nrow(APPL)) {
  if (APPL$Close[i] > APPL$Open[i+1]) {
      APPL$`"t1"`[i] = -1
  }
  else {
    APPL$`"t1"`[i] = 1
  }
}
```

```{r}
#t2
APPL <- cbind(APPL, "t2")
for (i in 1:nrow(APPL)) {
  if (APPL$Open[i] > APPL$Open[i+1]) {
     APPL$`"t2"`[i] = -1
  }
  else {
   APPL$`"t2"`[i] = 1
  }
}
```

```{r}
#t3
APPL <- cbind(APPL, "t3")
for (i in 1:nrow(APPL)) {
  if (APPL$Close[i] > APPL$Close[i+1]) {
      APPL$`"t3"`[i] = -1
  }
  else {
    APPL$`"t3"`[i] = 1
  }
}
```

```{r}
#t4
APPL <- cbind(APPL, "t4")
for (i in 1:nrow(APPL)) {
  if (APPL$Open[i] > APPL$Close[i+1]) {
      APPL$`"t4"`[i] = -1
  }
  else {
    APPL$`"t4"`[i] = 1
  }
}
```

```{r}
#t5
APPL <- cbind(APPL, "t5")
for (i in 1:nrow(APPL)) {
  if (APPL$Volume[i] > APPL$Volume[i+1]) {
      APPL$`"t5"`[i] = -1
  }
  else {
    APPL$`"t5"`[i] = 1
  }
}
```


```{r}
library(e1071)

APPL$`"t1"` = as.numeric(APPL$`"t1"`)
APPL$`"t2"` = as.numeric(APPL$`"t2"`)
APPL$`"t3"` = as.numeric(APPL$`"t3"`)
APPL$`"t4"` = as.numeric(APPL$`"t4"`)
APPL$`"t5"` = as.numeric(APPL$`"t5"`)
trainApple = APPL[1:554,]
testApple = APPL[555:737,]
# t1.svm
t1.svm = svm(`"t1"` ~ `"t2"` + `"t3"` + `"t4"` + `"t5"`, data = trainApple, scale = FALSE, kernel = "radial", type = "C")
summary(t1.svm)
yhat.t1.train.svm = predict(t1.svm)
yhat.t1.test.svm = predict(t1.svm, newdata = testApple)
yhat.t1.train.svm = as.numeric(yhat.t1.train.svm)
yhat.t1.test.svm = as.numeric(yhat.t1.test.svm)
t1.table = table(yhat.t1.train.svm, trainApple$`"t1"`)
t1.train.error = ((t1.table[1,2] + t1.table[2,1]) /nrow(trainApple))
t1.train.error
t1.test.table = table(yhat.t1.test.svm, testApple$`"t1"`)
t1.test.error = ((t1.test.table[1,2] + t1.test.table[2,1]) / nrow(testApple))
t1.test.error
```

```{r}
# t2.svm
t2.svm = svm(`"t2"` ~ `"t1"` + `"t3"` + `"t4"` + `"t5"`, data = trainApple, scale = FALSE, kernel = "radial", type = "C")
summary(t2.svm)
yhat.t2.train.svm = predict(t2.svm)
yhat.t2.test.svm = predict(t2.svm, newdata = testApple)
yhat.t2.train.svm = as.numeric(yhat.t2.train.svm)
yhat.t2.test.svm = as.numeric(yhat.t2.test.svm)
t2.table = table(yhat.t2.train.svm, trainApple$`"t2"`)
t2.train.error = ((t2.table[1,2] + t2.table[2,1]) /nrow(trainApple))
t2.train.error
t2.test.table = table(yhat.t2.test.svm, testApple$`"t2"`)
t2.test.error = ((t2.test.table[1,2] + t2.test.table[2,1]) / nrow(testApple))
t2.test.error
```

```{r}
# t3.svm
t3.svm = svm(`"t3"` ~ `"t1"` + `"t2"` + `"t4"` + `"t5"`, data = trainApple, scale = FALSE, kernel = "radial", type = "C")
summary(t3.svm)
yhat.t3.train.svm = predict(t3.svm)
yhat.t3.test.svm = predict(t3.svm, newdata = testApple)
yhat.t3.train.svm = as.numeric(yhat.t3.train.svm)
yhat.t3.test.svm = as.numeric(yhat.t3.test.svm)
t3.table = table(yhat.t3.train.svm, trainApple$`"t1"`)
t3.train.error = ((t3.table[1,2] + t3.table[2,1]) /nrow(trainApple))
t3.train.error
t3.test.table = table(yhat.t3.test.svm, testApple$`"t1"`)
t3.test.error = ((t3.test.table[1,2] + t3.test.table[2,1]) / nrow(testApple))
t3.test.error
```

```{r}
# t4.svm
t4.svm = svm(`"t4"` ~ `"t2"` + `"t3"` + `"t1"` + `"t5"`, data = trainApple, scale = FALSE, kernel = "radial", type = "C")
summary(t4.svm)
yhat.t4.train.svm = predict(t4.svm)
yhat.t4.test.svm = predict(t4.svm, newdata = testApple)
yhat.t4.train.svm = as.numeric(yhat.t4.train.svm)
yhat.t4.test.svm = as.numeric(yhat.t4.test.svm)
t4.table = table(yhat.t4.train.svm, trainApple$`"t1"`)
t4.train.error = ((t4.table[1,2] + t4.table[2,1]) /nrow(trainApple))
t4.train.error
t4.test.table = table(yhat.t4.test.svm, testApple$`"t1"`)
t4.test.error = ((t4.test.table[1,2] + t4.test.table[2,1]) / nrow(testApple))
t4.test.error
```

```{r}
# t5.svm
t5.svm = svm(`"t5"` ~ `"t2"` + `"t3"` + `"t4"` + `"t1"`, data = trainApple, scale = FALSE, kernel = "radial", type = "C")
summary(t5.svm)
yhat.t5.train.svm = predict(t5.svm)
yhat.t5.train.svm
yhat.t5.test.svm = predict(t5.svm, newdata = testApple)
yhat.t5.train.svm = as.numeric(yhat.t5.train.svm)
yhat.t5.test.svm = as.numeric(yhat.t5.test.svm)
t5.table = table(yhat.t5.train.svm, trainApple$`"t1"`)
t5.table
t5.train.error = ((t5.table[1,2] + t5.table[2,1]) /nrow(trainApple))
t5.train.error
t5.test.table = table(yhat.t5.test.svm, testApple$`"t1"`)
t5.test.error = ((t5.test.table[1,2] + t5.test.table[2,1]) / nrow(testApple))
t5.test.error
```

```{r}
#random forest and boosting with the targets
appl6 = APPL[,8:12]
colnames(appl6)[1] ="t1"
colnames(appl6)[2] ="t2"
colnames(appl6)[3] ="t3"
colnames(appl6)[4] ="t4"
colnames(appl6)[5] ="t5"
appl6$t1 = as.factor(appl6$t1)
appl6$t2 = as.factor(appl6$t2)
appl6$t3 = as.factor(appl6$t3)
appl6$t4 = as.factor(appl6$t4)
appl6$t5 = as.factor(appl6$t5)
library(tree)
trainTree = tree(t1 ~ t2 + t3 + t4 + t5, data = appl6)
plot(trainTree)
text(trainTree, pretty=0)
```

```{r}
library(gbm)
trainApple6 = appl6[1:554,]
testApple6 = appl6[555:773,]
boost.t1 = gbm(t1 ~ t2 + t3 + t4 + t5, data = trainApple6,
    distribution = "gaussian", n.trees = 1000,
    interaction.depth = 4)
#boost.t1$train.error
plot(1:1000, boost.t1$train.error)
summary(boost.t1)
```

```{r}
numtrees=1

yhat.train.temp = predict(boost.t1, newdata = trainApple6, n.trees = numtrees)
yhat.test.temp = predict(boost.t1, newdata = testApple6, n.trees = numtrees)
yhat.test.temp
temp.test.table = table(yhat.test.temp, testApple6$t1)
temp.test.table

split_val_test = 0
sum = 0
for (i in 1:length(yhat.train.temp)) {
  sum = sum + yhat.train.temp[i]
}
print(sum)
print(length(yhat.train.temp))
split_val_test = sum / length(yhat.train.temp)
split_val_test
yhat.test.temp <- as.factor(ifelse(yhat.test.temp>split_val_test,1,-1))
yhat.test.temp
temp.test.table = table(yhat.test.temp, testApple6$t1)
temp.test.table


temp.test.error = ((temp.test.table[1,2] + temp.test.table[2,1]) /nrow(testApple6))
temp.test.error
```

```{r}
testingTable = c()
for (treenum in 1:1000) {
  yhat.train.temp = predict(boost.t1, newdata = trainApple6, n.trees = treenum)
  yhat.test.temp = predict(boost.t1, newdata = testApple6, n.trees = treenum)
  yhat.test.temp
  temp.test.table = table(yhat.test.temp, testApple6$t1)
  temp.test.table
 
  split_val_test = 0
  sum = 0
  for (i in 1:length(yhat.train.temp)) {
    sum = sum + yhat.train.temp[i]
  }
  #split_val_test = sum / length(yhat.train.temp)
  split_val_test = median(yhat.train.temp)
  #print(split_val_test)
  yhat.test.temp <- as.factor(ifelse(yhat.test.temp>split_val_test,1,-1))
  yhat.test.temp
  temp.test.table = table(yhat.test.temp, testApple6$t1)
  temp.test.table
 
  temp.test.error = ((temp.test.table[1,2] + temp.test.table[2,1]) /nrow(testApple6))
  temp.test.error
  testingTable[treenum] = temp.test.error
}
# print(trainingTable)
# print(testingTable)
plot(1:1000, testingTable)
print(mean(testingTable))
print(min(testingTable))
```

```{r}
#boost t2
boost.t2 = gbm(t2 ~ t1 + t3 + t4 + t5, data = trainApple6,
    distribution = "gaussian", n.trees = 1000,
    interaction.depth = 4)
#boost.t1$train.error
plot(1:1000, boost.t2$train.error)
summary(boost.t2)

testingTable.t2 = c()
for (treenum in 1:1000) {
  yhat.train.temp.t2 = predict(boost.t2, newdata = trainApple6, n.trees = treenum)
  yhat.test.temp.t2 = predict(boost.t2, newdata = testApple6, n.trees = treenum)
  yhat.test.temp.t2
  temp.test.table.t2 = table(yhat.test.temp.t2, testApple6$t2)
  temp.test.table.t2
 
  split_val_test.t2 = 0
  sum.t2 = 0
  for (i in 1:length(yhat.train.temp.t2)) {
    sum.t2 = sum.t2 + yhat.train.temp.t2[i]
  }
  #split_val_test = sum / length(yhat.train.temp)
  split_val_test.t2 = median(yhat.train.temp.t2)
  #print(split_val_test)
  yhat.test.temp.t2 <- as.factor(ifelse(yhat.test.temp.t2>split_val_test.t2,1,-1))
  yhat.test.temp.t2
  temp.test.table.t2 = table(yhat.test.temp.t2, testApple6$t2)
  temp.test.table.t2
 
  temp.test.error.t2 = ((temp.test.table.t2[1,2] + temp.test.table.t2[2,1]) /nrow(testApple6))
  temp.test.error.t2
  testingTable.t2[treenum] = temp.test.error.t2
}
#print(trainingTable)
print(testingTable.t2)
plot(1:1000, testingTable.t2)
print(mean(testingTable.t2))
print(min(testingTable.t2))
```

```{r}
#boost t3
boost.t3 = gbm(t3 ~ t1 + t2 + t4 + t5, data = trainApple6,
    distribution = "gaussian", n.trees = 1000,
    interaction.depth = 4)
#boost.t1$train.error
plot(1:1000, boost.t3$train.error)
summary(boost.t3)

testingTable.t3 = c()
for (treenum in 1:1000) {
  yhat.train.temp.t3 = predict(boost.t3, newdata = trainApple6, n.trees = treenum)
  yhat.test.temp.t3 = predict(boost.t3, newdata = testApple6, n.trees = treenum)
  yhat.test.temp.t3
  temp.test.table.t3 = table(yhat.test.temp.t3, testApple6$t3)
  temp.test.table.t3
 
  split_val_test.t3 = 0
  sum.t3 = 0
  for (i in 1:length(yhat.train.temp.t3)) {
    sum.t3 = sum.t3 + yhat.train.temp.t3[i]
  }
  #split_val_test = sum / length(yhat.train.temp)
  split_val_test.t3 = median(yhat.train.temp.t3)
  #print(split_val_test)
  yhat.test.temp.t3 <- as.factor(ifelse(yhat.test.temp.t3>split_val_test.t3,1,-1))
  yhat.test.temp.t3
  temp.test.table.t3 = table(yhat.test.temp.t3, testApple6$t3)
  temp.test.table.t3
 
  temp.test.error.t3 = ((temp.test.table.t3[1,2] + temp.test.table.t3[2,1]) /nrow(testApple6))
  temp.test.error.t3
  testingTable.t3[treenum] = temp.test.error.t3
}
#print(trainingTable)
print(testingTable.t3)
plot(1:1000, testingTable.t3)
print(mean(testingTable.t3))
print(min(testingTable.t3))
```

```{r}
#boost t4
boost.t4 = gbm(t4 ~ t1 + t3 + t2 + t5, data = trainApple6,
    distribution = "gaussian", n.trees = 1000,
    interaction.depth = 4)
#boost.t1$train.error
plot(1:1000, boost.t4$train.error)
summary(boost.t4)

testingTable.t4 = c()
for (treenum in 1:1000) {
  yhat.train.temp.t4 = predict(boost.t4, newdata = trainApple6, n.trees = treenum)
  yhat.test.temp.t4 = predict(boost.t4, newdata = testApple6, n.trees = treenum)
  yhat.test.temp.t4
  temp.test.table.t4 = table(yhat.test.temp.t4, testApple6$t4)
  temp.test.table.t4
 
  split_val_test.t4 = 0
  sum.t4 = 0
  for (i in 1:length(yhat.train.temp.t4)) {
    sum.t4 = sum.t4 + yhat.train.temp.t4[i]
  }
  #split_val_test = sum / length(yhat.train.temp)
  split_val_test.t4 = median(yhat.train.temp.t4)
  #print(split_val_test)
  yhat.test.temp.t4 <- as.factor(ifelse(yhat.test.temp.t4>split_val_test.t4,1,-1))
  yhat.test.temp.t4
  temp.test.table.t4 = table(yhat.test.temp.t4, testApple6$t4)
  temp.test.table.t4
 
  temp.test.error.t4 = ((temp.test.table.t4[1,2] + temp.test.table.t4[2,1]) /nrow(testApple6))
  temp.test.error.t4
  testingTable.t4[treenum] = temp.test.error.t4
}
#print(trainingTable)
print(testingTable.t4)
plot(1:1000, testingTable.t4)
# index = c(1:1000)
# trainy = c(boost.t4$train.error)
# master = data.frame(index,trainy, testingTable.t4)
# master
plot(master$index, master$trainy, col = 'white', xlab = "Number of AdaBoost Trees", ylab = "Misclassification Rate")
lines(master$index, master$testingTable.t4, col = 'blue')
lines(master$index, master$trainy, col = 'red')
print(mean(testingTable.t4))
print(min(testingTable.t4))
```

```{r}
#boost t5
boost.t5 = gbm(t5 ~ t1 + t3 + t4 + t2, data = trainApple6,
    distribution = "gaussian", n.trees = 1000,
    interaction.depth = 4)
#boost.t1$train.error
plot(1:1000, boost.t5$train.error)
summary(boost.t5)

testingTable.t5 = c()
for (treenum in 1:1000) {
  yhat.train.temp.t5 = predict(boost.t5, newdata = trainApple6, n.trees = treenum)
  yhat.test.temp.t5 = predict(boost.t5, newdata = testApple6, n.trees = treenum)
  yhat.test.temp.t5
  temp.test.table.t5 = table(yhat.test.temp.t5, testApple6$t5)
  temp.test.table.t5
 
  split_val_test.t5 = 0
  sum.t5 = 0
  for (i in 1:length(yhat.train.temp.t5)) {
    sum.t5 = sum.t5 + yhat.train.temp.t5[i]
  }
  #split_val_test = sum / length(yhat.train.temp)
  split_val_test.t5 = median(yhat.train.temp.t5)
  #print(split_val_test)
  yhat.test.temp.t5 <- as.factor(ifelse(yhat.test.temp.t5>split_val_test.t5,1,-1))
  yhat.test.temp.t5
  temp.test.table.t5 = table(yhat.test.temp.t5, testApple6$t5)
  temp.test.table.t5
 
  temp.test.error.t5 = ((temp.test.table.t5[1,2] + temp.test.table.t5[2,1]) /nrow(testApple6))
  temp.test.error.t5
  testingTable.t5[treenum] = temp.test.error.t5
}
#print(trainingTable)
print(testingTable.t5)
plot(1:1000, testingTable.t5, main = "Target 5 Predictors")
print(mean(testingTable.t5))
print(min(testingTable.t5))
```
